### PR TITLE
From Buildr to Gradle & TCP management

### PR DESCRIPTION
**Pull request by JulienDeray**
## From Buildr to Gradle
- Dependencies are no longer in the repository but downloaded at build time.
- The root project and the 'testing' part have been splitted in two build.gradle files and linked by settings.gradle.
- The build is now launchable with `gradle build` or simply `gradle`
- All the tests in Buildr have been implemented in Gradle
- All the informations about the available tasks can be displayed by running `gradle tasks`
## TCP client

Jooflux now launches an internal TCP server when it starts. The client (see "client" folder) can connect to the server and send the same instructions as the JMX client does. Further details in the associated [README](https://github.com/Serli/jooflux/blob/buildr_to_gradle_and_tcp_management/client/README.md).

(cc @flemouel)

### CODE REVIEW

**Comment by jponge** [comment]
Thanks @JulienDeray we are going to review it with @flemouel :smiley: :+1:

**Comment by jponge** [comment]
I haven't checked the TCP stuff.

The Gradle build looks good basically, except that the output jar embeds JUnit + Hamcrest. This is weird, because you collect the dependencies from the `compile` configuration...

**Comment by JulienDeray** [comment]
Okay, I just saw that JsonSimple depends on JUnit ... Do you want me to use another lib ?

**Comment by jponge** [comment]
> Okay, I just saw that JsonSimple depends on JUnit ... Do you want me to use another lib ?

Can't you just exclude it? It would be simpler I think :smiley:

**Comment by JulienDeray** [comment]
Here it is :)

**Comment by jponge** [comment]
:+1:

**Comment by jponge** [comment]
@flemouel Looks good from my side.

**Comment by jponge** [comment]
Thanks a lot @JulienDeray :smiley:

**Comment by JulienDeray** [comment]
My pleasure !

**Pull request merged**
